### ISSUE TITLE
TypeError: Cannot call method 'trim' of undefined

### ISSUE THREAD

**Issue by nielk** [ymcatar/gitbook-plugin-mcqx#1] opened 2015-10-09 20:00 UTC
Firstly thank you for this plugin, It seems to fit perfectly my needs :)

But I encounter an issue when I try to add a mcq : 

```
{%mcq ans="o1", count=2%}
{%title%} This is a question?
{%o1%} First option
{%o2%} Second option
{%o3%} Third option
{%o4%} Fourth option
{%o5%} Fourth option
{%o6%} Fourth option
{%o7%} Fourth option
{%o8%} Fourth option
{%endmcq%}
```

This code throws an error : 

```
Template render error: (/Users/admin/repo/javascript/introduction/invention.md)
  TypeError: Cannot call method 'trim' of undefined (In file "introduction/invention.md")
```

**Comment by ymcatar** [comment] 2015-10-11 08:48
Currently I am quite busy with some other things, I will look into it later this week.

**Comment by ymcatar** [comment] 2015-10-17 14:30
I have added the code above into my test gitbook (https://ymcatar.gitbooks.io/gitbook-test/content/v/ef3c1cf88f838469635f8a738f0618d230cbd743/testing_mcqx.html), but I can't reproduce the problem.

**Comment by XieQirong** [comment] 2016-01-15 13:37
I got the same error, the version of gitbook which I'm using is 2.6.7

**Comment by ymcatar** [comment] 2016-01-17 12:03
I copied the code at the top into a fresh new gitbook (ver: 2.6.7), but I can't reproduce the problem. Can you tell me which version of node.js and the plugin you're using?

**Comment by XieQirong** [comment] 2016-01-17 12:22
Debian Jessie, Node.js v4.2.4, gitbook-plugin-mcqx 1.1.0

It can't work on gitbook.com as well, the same error

**Comment by XieQirong** [comment] 2016-01-18 03:02
I'm sorry, this is not a bug of this plugin, after I removed [plugin-exercises](https://github.com/GitbookIO/plugin-exercises) everything works well.

**Comment by ymcatar** [comment] 2016-01-18 03:09
Glad that you solved the problem. I will close the issue then.

**Closed by ymcatar** 2016-01-18 03:09 UTC
